### ISSUE TITLE
혹시 로아미터기 관련 포럼 있을까요

### ISSUE THREAD

**Issue by MarkShinCUHK** [MacColSolPep/loa-details-kr#1]
갤에서 보고왔는데 이미 opcode랑 다 바꼈을거 같아서 딱히 실행은 안해봤는데요
개인이 release 하신건지 아니면 어디 디코서버나 포럼 있을까요

**Comment by MacColSolPep** [comment]
제가 opcode랑 xor 뽑아서 사용하던거 릴리즈한거고
디코 서버는 음 현재 알려진 미터기 디코에서 대충 물어보고 다니면 어떤 사람이 흥미있냐면서 아마 초대 링크 dm 할껄요?
거기에서 몇몇개 도움 받았고

**Comment by MarkShinCUHK** [comment]
그렇군요. opcode랑 xor table은 LostarkDumper 쓰신건가요? 2년전에 업데이트가 중단되었는데 암호화 키가 안바뀌었나 해서요.

해외포럼 두개정도 들어가있는데 둘 다 한국인 사용자가 더이상 활동하지 않는 것 같아서요. 22년도에 마지막으로 한국인들이 남겼던 메세지가 몇 개 보이던데 너무 오래돼서 더 이상 활동하고 있는지 알수가 없네요.

**Comment by MarkShinCUHK** [comment]
감사합니다 더 자세히 알고싶은데 여기서 얘기하기 한계가 있는 것 같네요. 혹시 디코 서버 초대권한 있으시면 부탁드려봐도 될까요? 디코아이디 alskk199 입니다
